name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm clean-install
      - run: npm run build --if-present
      - run: npx sanity build --no-auto-updates --yes

      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag archiveslgbtqi:$(date +%s) --tag archiveslgbtqi:latest
