name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Clean Install
        run: npm clean-install

      - name: Build
        env: # Or as an environment variable
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
        run: npm run build --if-present

      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag archiveslgbtqi:$(date +%s) --tag archiveslgbtqi:latest
